import { defineConfig } from "vite";
import type { Plugin } from "vite";
import react from "@vitejs/plugin-react";

function offlineServiceWorker(): Plugin {
  return {
    name: "ghostline-offline-service-worker",
    generateBundle(_options, bundle) {
      const buildAssets = Object.keys(bundle)
        .filter((name) => /\.(?:js|css|woff2?|svg)$/.test(name))
        .map((name) => `/${name}`);
      const precache = ["/", "/index.html", "/manifest.webmanifest", ...buildAssets];
      const source = `/* generated by Vite: keep the complete app shell available offline */
const CACHE_NAME = "ghostline-shell-v2";
const APP_SHELL = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(APP_SHELL)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET" || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response.ok) caches.open(CACHE_NAME).then((cache) => cache.put(event.request, response.clone()));
        return response;
      }).catch(() => event.request.mode === "navigate" ? caches.match("/index.html") : Response.error());
    }),
  );
});
`;
      this.emitFile({ type: "asset", fileName: "sw.js", source });
    },
  };
}

export default defineConfig({
  plugins: [react(), offlineServiceWorker()],
  server: { host: "127.0.0.1" },
});
